#linux/arch/arm/mach-ak39/Makefile
#
# Copyright 2013 Anyka Microelectronics
#
# Licensed under GPLv2

obj-y               :=
obj-m               :=
obj-n               :=
obj-                :=

# Core support for all Anyka SoCs
obj-y			+= clock.o
