ak_venc-objs := ak-venc.o ak-venc-hw.o ak-venc-h264.o ak-venc-jpeg.o ak-venc-rc.o

obj-$(CONFIG_VIDEO_AK_VENC) += ak_venc.o

obj-$(CONFIG_VIDEO_AK_CAM_SENSOR) += ak-cam-sensor.o
obj-$(CONFIG_VIDEO_AK_CAM) += ak-cam.o
